'use client';

import {useEffect,useMemo,useState,type FormEvent,type ReactNode} from 'react';
import {LayoutDashboard,FileCheck2,Boxes,Building2,ArrowUpRight,ArrowRight,Download,Search,ChevronRight,ChevronLeft,Plus,SlidersHorizontal,Eye,ShieldCheck,CalendarClock,Clock3,Check,CheckCheck,TriangleAlert,FileText,History,Gauge,Thermometer,Wind,AudioLines,Weight,Info,LogOut,HelpCircle,Upload,Copy,Link2,LoaderCircle,X,MapPin,FolderOpen,RefreshCw,UserRound,MoreHorizontal} from 'lucide-react';
import {Sidebar,SidebarContent,SidebarFooter,SidebarHeader,SidebarProvider,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarGroup,SidebarGroupLabel,SidebarTrigger,useSidebar} from '@/components/ui/sidebar';
import {Table,TableHeader,TableHead,TableRow,TableCell,TableBody} from '@/components/ui/table';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {DropdownMenu,DropdownMenuTrigger,DropdownMenuContent,DropdownMenuItem,DropdownMenuLabel,DropdownMenuSeparator} from '@/components/ui/dropdown-menu';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {Empty,EmptyHeader,EmptyTitle,EmptyDescription,EmptyMedia} from '@/components/ui/empty';
import {Pagination,PaginationContent,PaginationItem} from '@/components/ui/pagination';
import {Skeleton} from '@/components/ui/skeleton';
import {Toaster,toast} from 'sonner';
import {categories,dateLabel,daysUntil,emptyData,latestFor,makeDemo,normalize,statusFor,today,type PortalData,type Equipment,type Certificate,type Company,type Member} from '@/lib/portal-shared';

type View = 'overview'|'certificates'|'equipment'|'clients';
type Modal = 'company'|'equipment'|'certificate'|'help'|'access'|null;
const views:Record<View,{label:string;icon:typeof LayoutDashboard}>={overview:{label:'Visão geral',icon:LayoutDashboard},certificates:{label:'Certificados',icon:FileCheck2},equipment:{label:'Equipamentos',icon:Boxes},clients:{label:'Clientes e acessos',icon:Building2}};

function EquipmentIcon({category,...props}:{category:string;className?:string;size?:number}){const Icon=category==='Termômetro'?Thermometer:category==='Detector de gás'?Wind:category==='Bafômetro'?Gauge:category==='Dinamômetro'?Weight:AudioLines;return <Icon {...props}/>;}
function Status({cert}:{cert?:Certificate}){const s=statusFor(cert);return <span className={`status ${s.tone}`}>{s.key==='ok'?<Check size={12}/>:s.key==='overdue'?<Clock3 size={12}/>:s.key==='soon'?<CalendarClock size={12}/>:null}{s.label}</span>;}
function Picker({value,onChange,options,label,className='',name,defaultValue,required}:{value?:string;onChange?:(v:string)=>void;options:{value:string;label:string}[];label:string;className?:string;name?:string;defaultValue?:string;required?:boolean}){return <Select value={value} onValueChange={onChange} name={name} defaultValue={defaultValue} required={required}><SelectTrigger aria-label={label} className={className}><SelectValue placeholder={label}/></SelectTrigger><SelectContent position="popper">{options.map(o=><SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>)}</SelectContent></Select>;}
function Field({label,children,optional}:{label:string;children:ReactNode;optional?:boolean}){return <label className="form-field"><span>{label}{optional&&<small>Opcional</small>}</span>{children}</label>;}
function Nav({view,go,admin,help}:{view:View;go:(v:View)=>void;admin:boolean;help:()=>void}){
  const {setOpenMobile}=useSidebar();
  const navigate=(v:View)=>{go(v);setOpenMobile(false);};
  return <Sidebar className="brand-sidebar"><SidebarHeader className="brand-header"><a href="/" className="brand" aria-label="Central Brasil — início"><span className="brand-mark"><Gauge size={26} strokeWidth={2}/></span><span>CENTRAL<span>BRASIL<span className="brand-word-small"> INSTRUMENTOS</span></span></span></a><div className="portal-label">PORTAL DE CERTIFICADOS</div></SidebarHeader><SidebarContent><SidebarGroup><SidebarGroupLabel className="nav-label">ÁREA DO CLIENTE</SidebarGroupLabel><SidebarMenu>{(['overview','certificates','equipment'] as View[]).map(v=>{const Icon=views[v].icon;return <SidebarMenuItem key={v}><SidebarMenuButton className="nav-item" isActive={view===v} onClick={()=>navigate(v)}><Icon/><span>{views[v].label}</span>{view===v&&<ChevronRight className="nav-chevron" size={15}/>}</SidebarMenuButton></SidebarMenuItem>;})}</SidebarMenu></SidebarGroup>{admin&&<SidebarGroup className="management-nav"><SidebarGroupLabel className="nav-label">ADMINISTRAÇÃO</SidebarGroupLabel><SidebarMenu><SidebarMenuItem><SidebarMenuButton className="nav-item" isActive={view==='clients'} onClick={()=>navigate('clients')}><Building2/><span>Clientes e acessos</span></SidebarMenuButton></SidebarMenuItem></SidebarMenu></SidebarGroup>}</SidebarContent><SidebarFooter className="sidebar-bottom"><div className="sidebar-help"><span className="help-symbol"><ShieldCheck size={23}/></span><h3>Precisão em cada etapa.</h3><p>Seus documentos organizados.<br/>Seu histórico sempre acessível.</p><button onClick={help}>Como usar o portal <ArrowUpRight size={16}/></button></div><div className="sidebar-footer-note"><ShieldCheck size={14}/><span>Acesso protegido</span></div></SidebarFooter></Sidebar>;
}

async function api<T=Record<string,unknown>>(url:string,options?:RequestInit):Promise<T>{
  const res=await fetch(url,options);let data:Record<string,unknown>;try{data=await res.json() as Record<string,unknown>;}catch{throw new Error('Não foi possível acessar o portal. Tente novamente.');}
  if(!res.ok)throw new Error(typeof data.error==='string'?data.error:'Não foi possível concluir a solicitação.');return data as T;
}
function jsonPost(data:unknown,method='POST'):RequestInit{return {method,headers:{'Content-Type':'application/json'},body:JSON.stringify(data)};}
function saveBlob(blob:Blob,name:string){const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);}
function demoPDF(cert:Certificate,equipment:Equipment){
  const ascii=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^\x20-\x7e]/g,'').replace(/[()\\]/g,'\\$&');
  const lines=['CENTRAL BRASIL INSTRUMENTOS','PORTAL DE CERTIFICADOS','DOCUMENTO DEMONSTRATIVO - SEM VALIDADE METROLOGICA','',`Registro de exemplo: ${cert.number}`,`Equipamento: ${equipment.name}`,`Numero de serie: ${equipment.serial}`,`Calibracao de exemplo: ${dateLabel(cert.calibratedAt)}`,`Proxima calibracao de exemplo: ${dateLabel(cert.nextAt)}`,'','Este PDF permite testar a visualizacao e o download.','Nao representa uma calibracao realizada nem certifica um equipamento.','Para uso operacional, envie o certificado original emitido pelo laboratorio.'];
  const stream='BT /F1 12 Tf 50 790 Td 22 TL '+lines.map((s,i)=>(i?'T* ':'')+'('+ascii(s)+') Tj').join('\n')+' ET';
  const objects=['<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Kids [3 0 R] /Count 1 >>','<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>','<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',`<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`];
  let pdf='%PDF-1.4\n';const offsets=[0];objects.forEach((o,i)=>{offsets.push(pdf.length);pdf+=`${i+1} 0 obj\n${o}\nendobj\n`;});const xref=pdf.length;pdf+='xref\n0 6\n0000000000 65535 f \n'+offsets.slice(1).map(n=>String(n).padStart(10,'0')+' 00000 n \n').join('');pdf+=`trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;return new Blob([pdf],{type:'application/pdf'});
}

export default function Portal({user}:{user:{name:string;email:string}}){
  const [real,setReal]=useState<PortalData>(emptyData);const [demoData]=useState(makeDemo);const [demo,setDemo]=useState(true);const [loading,setLoading]=useState(true);const [loadError,setLoadError]=useState('');
  const [view,setView]=useState<View>('overview');const [companyId,setCompanyId]=useState('all');const [query,setQuery]=useState('');const [category,setCategory]=useState('all');const [status,setStatus]=useState('all');const [year,setYear]=useState('all');const [page,setPage]=useState(1);
  const [modal,setModal]=useState<Modal>(null);const [selected,setSelected]=useState<Equipment|null>(null);const [selectedCert,setSelectedCert]=useState<string|null>(null);const [busy,setBusy]=useState(false);const [formError,setFormError]=useState('');const [pdf,setPdf]=useState<{url:string;number:string}|null>(null);const [pdfBusy,setPdfBusy]=useState<string|null>(null);const [invitation,setInvitation]=useState<{code:string;expiresAt:string;company:Company}|null>(null);const [revoke,setRevoke]=useState<Member|null>(null);
  const data=demo?demoData:real;const isAdmin=real.role==='admin';
  async function refresh(initial=false){setLoading(true);setLoadError('');try{const result=await api<PortalData>('/api/portal');setReal(result);if(initial&&(result.companies.length>0||result.role!=='admin'))setDemo(false);return result;}catch(e){setLoadError((e as Error).message);return null;}finally{setLoading(false);}}
  useEffect(()=>{void refresh(true);},[]);
  useEffect(()=>{setPage(1);},[query,category,status,year,view,companyId,demo]);
  useEffect(()=>()=>{if(pdf)URL.revokeObjectURL(pdf.url);},[pdf]);
  function go(v:View){setView(v);setQuery('');setStatus('all');setYear('all');setCategory('all');setPage(1);}
  function setMode(nextDemo:boolean){setDemo(nextDemo);setCompanyId('all');setSelected(null);go('overview');}
  function openModal(m:Modal){setFormError('');setModal(m);}
  function startAdd(m:'company'|'equipment'|'certificate'){
    if(!isAdmin){toast.error(loading?'Aguarde o carregamento dos seus acessos.':'Somente a administração pode cadastrar documentos.');return;}
    if(demo){setDemo(false);setCompanyId('all');}
    if(m!=='company'&&!real.companies.length){go('clients');openModal('company');toast.info('Cadastre o primeiro cliente para continuar.');return;}
    if(m==='certificate'&&!real.equipment.length){go('equipment');openModal('equipment');toast.info('Cadastre um equipamento para vincular o certificado.');return;}openModal(m);
  }
  const equipment=useMemo(()=>data.equipment.filter(e=>companyId==='all'||e.companyId===companyId),[data,companyId]);
  const certificates=useMemo(()=>data.certificates.filter(c=>equipment.some(e=>e.id===c.equipmentId)).sort((a,b)=>b.calibratedAt.localeCompare(a.calibratedAt)||b.createdAt.localeCompare(a.createdAt)),[data,equipment]);
  const latest=equipment.map(e=>({equipment:e,cert:latestFor(e.id,certificates)}));
  const due=latest.filter(x=>x.cert?.nextAt&&daysUntil(x.cert.nextAt)<=30).sort((a,b)=>a.cert!.nextAt.localeCompare(b.cert!.nextAt));
  const soon=latest.filter(x=>statusFor(x.cert).key==='soon').length;const overdue=latest.filter(x=>statusFor(x.cert).key==='overdue').length;const ok=latest.filter(x=>statusFor(x.cert).key==='ok').length;const unscheduled=equipment.length-soon-overdue-ok;
  const queryMatches=(e:Equipment,c?:Certificate)=>normalize([e.name,e.serial,e.tag,e.model,e.brand,c?.number||''].join(' ')).includes(normalize(query));
  const filteredEquipment=equipment.filter(e=>queryMatches(e)&& (category==='all'||e.category===category)&&(status==='all'||statusFor(latestFor(e.id,certificates)).key===status));
  const filteredCerts=certificates.filter(c=>{const e=equipment.find(e=>e.id===c.equipmentId)!;return queryMatches(e,c)&&(category==='all'||e.category===category)&&(year==='all'||c.calibratedAt.startsWith(year))&&(status==='all'||(latestFor(e.id,certificates)?.id===c.id&&statusFor(c).key===status));});
  const visibleCerts=view==='overview'?filteredCerts.slice(0,5):filteredCerts.slice((page-1)*8,page*8);
  const displayCompany=companyId==='all'?(data.companies.length===1?data.companies[0].name:'Todos os clientes'):data.companies.find(c=>c.id===companyId)?.name||'Cliente';
  const title=view==='overview'?'Controle de calibrações':view==='certificates'?'Seus certificados':view==='equipment'?'Seus equipamentos':'Clientes e acessos';
  const descriptions={overview:'Uma visão completa dos seus equipamentos e certificados.',certificates:'Consulte, visualize e baixe seus documentos de calibração.',equipment:'Acompanhe cada equipamento, do cadastro ao histórico.',clients:'Organize os documentos e o acesso de cada cliente.'};
  function details(e:Equipment,c?:Certificate){setSelected(e);setSelectedCert(c?.id||null);}
  async function openPdf(c:Certificate,download=false){
    setPdfBusy(c.id);try{let blob:Blob;if(demo){blob=demoPDF(c,data.equipment.find(e=>e.id===c.equipmentId)!);}else{const res=await fetch(`/api/certificates/${encodeURIComponent(c.id)}`);if(!res.ok){const error=await res.json() as {error?:string};throw new Error(error.error||'Arquivo indisponível.');}blob=await res.blob();}if(download){saveBlob(blob,`${demo?'DEMONSTRACAO-':''}${c.number.replace(/[^a-zA-Z0-9_-]/g,'_')}.pdf`);toast.success('Download iniciado.');}else{setPdf({url:URL.createObjectURL(blob),number:c.number});}}catch(e){toast.error((e as Error).message);}finally{setPdfBusy(null);}
  }
  function exportList(){
    const header=['Certificado','Equipamento','Número de série','Patrimônio','Cliente','Calibração','Próxima calibração','Registro'];
    const rows=filteredCerts.map(c=>{const e=equipment.find(e=>e.id===c.equipmentId)!;return [c.number,e.name,e.serial,e.tag,data.companies.find(co=>co.id===e.companyId)?.name||'',dateLabel(c.calibratedAt),dateLabel(c.nextAt),demo?'DEMONSTRAÇÃO':'Original enviado'];});
    const cell=(v:string)=>'"'+(/^[=+\-@\t\r]/.test(v)?"'"+v:v).replace(/"/g,'""')+'"';
    saveBlob(new Blob(['\uFEFF'+[header,...rows].map(row=>row.map(cell).join(';')).join('\r\n')],{type:'text/csv;charset=utf-8'}),`central-brasil-certificados${demo?'-demonstracao':''}.csv`);toast.success(`${rows.length} certificados exportados.`);
  }
  async function submit(event:FormEvent<HTMLFormElement>,kind:Modal){
    event.preventDefault();if(busy)return;setBusy(true);setFormError('');const form=new FormData(event.currentTarget);
    try{
      if(kind==='certificate')await api('/api/certificates',{method:'POST',body:form});
      else await api(kind==='company'?'/api/companies':kind==='equipment'?'/api/equipment':'/api/access',jsonPost(Object.fromEntries(form.entries())));
      setModal(null);setDemo(false);setCompanyId('all');await refresh();toast.success(kind==='certificate'?'Certificado adicionado ao histórico.':kind==='access'?'Acesso vinculado à sua empresa.':'Cadastro salvo.');
    }catch(e){setFormError((e as Error).message);}finally{setBusy(false);}
  }
  async function invite(company:Company){if(demo){toast.info('Os códigos de acesso ficam disponíveis após cadastrar um cliente real.');return;}setBusy(true);try{const result=await api<{code:string;expiresAt:string}>('/api/invitations',jsonPost({companyId:company.id}));setInvitation({...result,company});}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}}
  async function revokeMember(){if(!revoke)return;setBusy(true);try{await api('/api/members',jsonPost({userId:revoke.userId},'DELETE'));setRevoke(null);await refresh();toast.success('Acesso removido.');}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}}
  useEffect(()=>{
    const context=(document as Document&{modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>unknown}}).modelContext;
    if(!context?.registerTool)return;const lifecycle=new AbortController();
    const tools=[{name:'search_certificates',title:'Buscar certificados',description:'Filtra a lista visível de certificados pelo número, equipamento ou série. Não modifica documentos.',inputSchema:{type:'object',properties:{query:{type:'string',maxLength:200}},required:['query'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute(input:unknown){const q=(input as {query?:unknown})?.query;if(typeof q!=='string'||q.length>200)throw new Error('Informe uma busca de até 200 caracteres.');go('certificates');setQuery(q);return {query:q,demo,matches:certificates.filter(c=>{const e=equipment.find(e=>e.id===c.equipmentId)!;return normalize(`${c.number} ${e.name} ${e.serial} ${e.tag} ${e.model} ${e.brand}`).includes(normalize(q));}).map(c=>({number:c.number,equipmentId:c.equipmentId,calibratedAt:c.calibratedAt}))};}},
    {name:'open_equipment_history',title:'Abrir histórico do equipamento',description:'Abre o painel visível com os certificados do equipamento selecionado. O identificador é o ID interno do equipamento.',inputSchema:{type:'object',properties:{equipmentId:{type:'string'}},required:['equipmentId'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute(input:unknown){const id=(input as {equipmentId?:unknown})?.equipmentId;if(typeof id!=='string')throw new Error('Informe o ID do equipamento.');const e=equipment.find(e=>e.id===id);if(!e)throw new Error('Equipamento não encontrado neste acesso.');details(e);return {equipment:e.name,serial:e.serial,demo,certificates:certificates.filter(c=>c.equipmentId===id).map(c=>({number:c.number,calibratedAt:c.calibratedAt}))};}}];
    tools.forEach(t=>{try{void Promise.resolve(context.registerTool(t,{signal:lifecycle.signal})).catch(()=>{});}catch{}});return ()=>lifecycle.abort();
  },[data,companyId,demo]);

  function CertTable(){return <Table className="cert-table"><TableHeader><TableRow><TableHead>Certificado / equipamento</TableHead><TableHead>Número de série</TableHead><TableHead>Calibração</TableHead>{view!=='overview'&&<TableHead>Próxima calibração</TableHead>}<TableHead>Programação</TableHead><TableHead className="text-right">Ações</TableHead></TableRow></TableHeader><TableBody>{visibleCerts.map(c=>{const e=equipment.find(e=>e.id===c.equipmentId)!;const historical=latestFor(e.id,certificates)?.id!==c.id;return <TableRow key={c.id}><TableCell><button className="certificate-name" onClick={()=>details(e,c)}><span className="document-icon"><FileText size={20}/></span><span><strong>{c.number}</strong><small>{e.name}</small></span></button></TableCell><TableCell><span className="serial">{e.serial}</span><small className="table-sub">{e.tag||'Sem patrimônio'}</small></TableCell><TableCell>{dateLabel(c.calibratedAt)}</TableCell>{view!=='overview'&&<TableCell>{dateLabel(c.nextAt)}</TableCell>}<TableCell>{historical?<span className="status neutral"><History size={12}/>Histórico</span>:<Status cert={c}/>}</TableCell><TableCell><div className="table-actions"><button className="icon-button" title={`Visualizar ${c.number}`} aria-label={`Visualizar ${c.number}`} disabled={pdfBusy===c.id} onClick={()=>openPdf(c)}>{pdfBusy===c.id?<LoaderCircle size={17} className="animate-spin"/>:<Eye size={17}/>}</button><button className="icon-button" title={`Baixar ${c.number}`} aria-label={`Baixar ${c.number}`} disabled={pdfBusy===c.id} onClick={()=>openPdf(c,true)}><Download size={17}/></button><button className="icon-button detail-action" title="Ver histórico do equipamento" aria-label={`Ver histórico de ${e.serial}`} onClick={()=>details(e,c)}><ChevronRight size={17}/></button></div></TableCell></TableRow>;})}</TableBody></Table>;}
  const blank=(heading:string,description:string,action?:ReactNode)=><Empty className="empty-state"><EmptyHeader><EmptyMedia variant="icon"><FolderOpen/></EmptyMedia><EmptyTitle>{heading}</EmptyTitle><EmptyDescription>{description}</EmptyDescription></EmptyHeader>{action}</Empty>;

  return <SidebarProvider style={{'--sidebar-width':'248px'} as React.CSSProperties}><a className="skip-link" href="#main-content">Ir para o conteúdo</a><Nav view={view} go={go} admin={isAdmin||demo} help={()=>openModal('help')}/><div className="app-shell"><header className="topbar"><div className="breadcrumb"><SidebarTrigger className="mobile-menu"/><span>Portal do cliente</span><ChevronRight size={14}/><strong>{views[view].label}</strong></div><div className="topbar-right">{loading?<span className="loading-label"><LoaderCircle size={14} className="animate-spin"/>Carregando</span>:isAdmin&&<button className={'mode-pill '+(demo?'demo':'')} onClick={()=>setMode(!demo)}><span/>{demo?'Demonstração':'Dados reais'}</button>}<button className="icon-button help-top" aria-label="Ajuda" onClick={()=>openModal('help')}><HelpCircle size={19}/></button><span className="topbar-divider"/><DropdownMenu><DropdownMenuTrigger asChild><button className="account-button" aria-label="Abrir minha conta"><span className="avatar">{user.name==='Minha conta'?'CB':user.name.slice(0,2).toUpperCase()}</span><span className="account-text"><strong>{user.name}</strong><small>{isAdmin?'Administrador':'Área do cliente'}</small></span><ChevronRight size={15}/></button></DropdownMenuTrigger><DropdownMenuContent align="end" className="max-w-[300px]"><DropdownMenuLabel className="break-all">{user.email}</DropdownMenuLabel><DropdownMenuSeparator/>{isAdmin&&<DropdownMenuItem onClick={()=>setMode(!demo)}>{demo?'Acessar dados reais':'Ver demonstração'}</DropdownMenuItem>}<DropdownMenuItem asChild><a href="/signout-with-chatgpt?return_to=%2F" target="_top"><LogOut size={15}/>Sair da conta</a></DropdownMenuItem></DropdownMenuContent></DropdownMenu></div></header>
    <main id="main-content" className="main-content">
      {loadError&&<div className="error-banner" role="alert"><TriangleAlert size={18}/><span>{loadError}</span><button onClick={()=>refresh()}>Tentar novamente</button></div>}
      {demo&&<div className="demo-notice"><Info size={15}/><span>Você está explorando uma demonstração com dados fictícios.</span>{isAdmin&&<button onClick={()=>setMode(false)}>Usar meus dados <ArrowRight size={14}/></button>}</div>}
      {!demo&&real.role==='pending'&&!loading?<section className="access-state"><span className="access-icon"><ShieldCheck size={34}/></span><p className="eyebrow">CENTRAL BRASIL INSTRUMENTOS</p><h1>Seu acesso começa aqui.</h1><p>Informe o código recebido da Central Brasil para consultar os certificados da sua empresa.</p><button className="button primary" onClick={()=>openModal('access')}><Link2 size={17}/>Vincular meu acesso</button><button className="text-button" onClick={()=>openModal('help')}>Como funciona?</button></section>:<>
      <div className="page-heading"><div><p className="eyebrow">CENTRAL BRASIL INSTRUMENTOS</p><h1>{title}</h1><p className="page-description">{descriptions[view]}</p></div><div className="heading-actions">{view!=='clients'&&<button className="button outline" onClick={exportList} disabled={!certificates.length}><Download size={16}/><span>Exportar lista</span></button>}{(isAdmin||demo)&&<button className="button primary" disabled={loading||!isAdmin} onClick={()=>startAdd(view==='clients'?'company':view==='equipment'?'equipment':'certificate')}><Plus size={18}/>{view==='clients'?'Novo cliente':view==='equipment'?'Novo equipamento':'Novo certificado'}</button>}</div></div>
      <div className="context-row"><div className="company-context"><Building2 size={16}/>{data.companies.length>1?<Picker label="Cliente" value={companyId} onChange={setCompanyId} className="company-picker" options={[{value:'all',label:'Todos os clientes'},...data.companies.map(c=>({value:c.id,label:c.name}))]}/>:<strong>{displayCompany==='Todos os clientes'?'Central Brasil Instrumentos':displayCompany}</strong>}{demo&&<span className="context-tag">EXEMPLO</span>}</div><div className="today-date"><CalendarClock size={14}/>{new Date().toLocaleDateString('pt-BR',{day:'numeric',month:'long',year:'numeric',timeZone:'UTC'})}</div></div>
      {view==='overview'&&<>
        <section className="stats-grid" aria-label="Resumo das calibrações"><button className="stat-card" onClick={()=>go('equipment')}><div className="stat-top"><span>Equipamentos</span><span className="stat-icon forest"><Boxes size={21}/></span></div><strong>{equipment.length.toString().padStart(2,'0')}</strong><div className="stat-bottom"><span>Cadastrados no portal</span><ArrowUpRight size={17}/></div></button><button className="stat-card" onClick={()=>go('certificates')}><div className="stat-top"><span>Certificados</span><span className="stat-icon blue"><FileCheck2 size={21}/></span></div><strong>{certificates.length.toString().padStart(2,'0')}</strong><div className="stat-bottom"><span>Disponíveis para consulta</span><ArrowUpRight size={17}/></div></button><button className="stat-card" onClick={()=>{go('equipment');setStatus('soon');}}><div className="stat-top"><span>Próximas calibrações</span><span className="stat-icon amber"><CalendarClock size={21}/></span></div><strong>{soon.toString().padStart(2,'0')}</strong><div className="stat-bottom"><span>Nos próximos 30 dias</span><ArrowUpRight size={17}/></div></button><button className="stat-card" onClick={()=>{go('equipment');setStatus('overdue');}}><div className="stat-top"><span>Calibrações pendentes</span><span className="stat-icon red"><Clock3 size={21}/></span></div><strong>{overdue.toString().padStart(2,'0')}</strong><div className="stat-bottom"><span>Requerem atenção</span><ArrowUpRight size={17}/></div></button></section>
        {overdue>0&&<div className="attention-banner"><span className="attention-icon"><TriangleAlert size={19}/></span><div><strong>{overdue===1?'Um equipamento precisa de atenção.':`${overdue} equipamentos precisam de atenção.`}</strong><span> A data programada para a próxima calibração já passou.</span></div><button onClick={()=>{go('equipment');setStatus('overdue');}}>Ver equipamento{overdue>1?'s':''}<ArrowRight size={16}/></button></div>}
        {!demo&&!equipment.length&&!loading&&<div className="setup-banner"><span className="setup-icon"><FolderOpen size={27}/></span><div><h2>Vamos organizar seus primeiros certificados?</h2><p>Cadastre o cliente, adicione o equipamento e envie o PDF do certificado.</p></div>{isAdmin&&<button className="button primary" onClick={()=>startAdd(real.companies.length?'equipment':'company')}>Começar cadastro <ArrowRight size={16}/></button>}</div>}
        <div className="dashboard-columns"><section className="panel recent-panel"><div className="panel-heading"><div><h2>Certificados recentes <span className="count-label">{certificates.length}</span></h2><p>Seus últimos documentos de calibração</p></div><button className="text-button" onClick={()=>go('certificates')}>Ver todos <ArrowRight size={15}/></button></div><div className="quick-search"><Search size={17}/><input aria-label="Buscar certificados recentes" placeholder="Buscar certificado, equipamento ou número de série..." value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button aria-label="Limpar busca" onClick={()=>setQuery('')}><X size={15}/></button>}</div>{visibleCerts.length?<CertTable/>:loading&&!demo?<div className="table-loading"><Skeleton className="h-12"/><Skeleton className="h-12"/><Skeleton className="h-12"/></div>:blank(query?'Nenhum certificado encontrado':'Nenhum certificado por aqui',query?'Tente outro número de série ou nome de equipamento.':'Os documentos adicionados aparecerão aqui.')}<div className="panel-foot"><ShieldCheck size={14}/><span>{demo?'Documentos ilustrativos para explorar o portal':'Arquivos originais enviados pela administração'}</span></div></section>
        <aside className="right-column"><section className="panel schedule-panel"><div className="panel-heading"><div><span className="section-kicker">SEU PLANEJAMENTO</span><h2>Próximas calibrações</h2></div><CalendarClock size={21}/></div><div className="schedule-list">{due.length?due.slice(0,3).map(({equipment:e,cert:c})=>{const days=daysUntil(c!.nextAt);const d=new Date(c!.nextAt+'T12:00:00Z');return <button className="schedule-item" key={e.id} onClick={()=>details(e)}><div className={'date-block '+(days<0?'late':'')}><span>{d.toLocaleDateString('pt-BR',{month:'short',timeZone:'UTC'}).replace('.','').toUpperCase()}</span><strong>{d.getUTCDate()}</strong></div><div><strong>{e.name}</strong><small>{e.serial}</small><span className={days<0?'due-red':'due-amber'}>{days<0?`${Math.abs(days)} dias em atraso`:days===0?'Programada para hoje':`Em ${days} dias`}</span></div><ChevronRight size={15}/></button>}):<p className="schedule-empty">Nenhuma calibração programada para os próximos 30 dias.</p>}</div><button className="schedule-footer" onClick={()=>{go('equipment');setStatus(due.length&&overdue?'overdue':due.length?'soon':'all');}}>Consultar programação <ArrowRight size={15}/></button></section><section className="compliance-panel"><div><ShieldCheck size={21}/><span>Programação de calibração</span></div><h3>{equipment.length?Math.round(ok/equipment.length*100):0}<small>%</small><span>em dia</span></h3><div className="segmented-track" aria-label={`${ok} em dia, ${soon} próximas, ${overdue} pendentes, ${unscheduled} sem programação`}>{[['ok',ok],['soon',soon],['overdue',overdue],['unscheduled',unscheduled]].map(([k,n])=>Number(n)>0&&<span key={k} className={String(k)} style={{flex:Number(n)}}/>)}</div><div className="compliance-legend"><span><i className="ok"/>{ok} em dia</span><span><i className="soon"/>{soon} próximas</span><span><i className="overdue"/>{overdue} pendentes</span>{unscheduled>0&&<span><i className="unscheduled"/>{unscheduled} sem data</span>}</div><p>Com base na próxima calibração informada.</p></section></aside></div>
      </>}
      {view==='certificates'&&<section className="panel full-panel"><div className="filter-toolbar"><div className="quick-search"><Search size={17}/><input aria-label="Buscar certificados" placeholder="Certificado, equipamento, série ou patrimônio..." value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button aria-label="Limpar busca" onClick={()=>setQuery('')}><X size={15}/></button>}</div><Picker label="Categoria" value={category} onChange={setCategory} options={[{value:'all',label:'Todas as categorias'},...categories.map(c=>({value:c,label:c}))]}/><Picker label="Ano da calibração" value={year} onChange={setYear} options={[{value:'all',label:'Todos os anos'},...Array.from(new Set(certificates.map(c=>c.calibratedAt.slice(0,4)))).sort().reverse().map(y=>({value:y,label:y}))]}/></div><Tabs value={status} onValueChange={setStatus} className="filter-tabs"><TabsList variant="line"><TabsTrigger value="all">Todos <span>{certificates.length}</span></TabsTrigger><TabsTrigger value="ok">Em dia</TabsTrigger><TabsTrigger value="soon">Em até 30 dias</TabsTrigger><TabsTrigger value="overdue">Pendentes</TabsTrigger></TabsList></Tabs>{visibleCerts.length?<CertTable/>:blank('Nenhum certificado encontrado','Ajuste os filtros ou adicione o primeiro certificado.',(query||category!=='all'||status!=='all'||year!=='all')?<button className="button outline" onClick={()=>{setQuery('');setCategory('all');setStatus('all');setYear('all');}}>Limpar filtros</button>:isAdmin?<button className="button primary" onClick={()=>startAdd('certificate')}><Plus size={16}/>Adicionar certificado</button>:undefined)}<div className="pagination-row"><span>{filteredCerts.length?`${(page-1)*8+1}–${Math.min(page*8,filteredCerts.length)} de ${filteredCerts.length}`:'0'} certificados</span><Pagination aria-label="Paginação de certificados" className="page-navigation"><PaginationContent><PaginationItem><button className="icon-button" disabled={page===1} aria-label="Página anterior" onClick={()=>setPage(p=>p-1)}><ChevronLeft size={17}/></button></PaginationItem><PaginationItem><span>Página {page} de {Math.max(1,Math.ceil(filteredCerts.length/8))}</span></PaginationItem><PaginationItem><button className="icon-button" disabled={page*8>=filteredCerts.length} aria-label="Próxima página" onClick={()=>setPage(p=>p+1)}><ChevronRight size={17}/></button></PaginationItem></PaginationContent></Pagination></div></section>}
      {view==='equipment'&&<><div className="equipment-toolbar"><div className="quick-search"><Search size={17}/><input aria-label="Buscar equipamentos" placeholder="Buscar nome, número de série ou patrimônio..." value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button aria-label="Limpar busca" onClick={()=>setQuery('')}><X size={15}/></button>}</div><Picker label="Categoria" value={category} onChange={setCategory} options={[{value:'all',label:'Todas as categorias'},...categories.map(c=>({value:c,label:c}))]}/><Picker label="Programação" value={status} onChange={setStatus} options={[{value:'all',label:'Toda a programação'},{value:'ok',label:'Em dia'},{value:'soon',label:'Em até 30 dias'},{value:'overdue',label:'Pendentes'},{value:'none',label:'Sem certificado'},{value:'unscheduled',label:'Sem programação'}]}/></div><div className="results-caption">{filteredEquipment.length} equipamento{filteredEquipment.length!==1?'s':''} encontrado{filteredEquipment.length!==1?'s':''}</div>{filteredEquipment.length?<div className="equipment-grid">{filteredEquipment.map(e=>{const cert=latestFor(e.id,certificates);return <article className="equipment-card" key={e.id}><div className="equipment-top"><span className="equipment-icon"><EquipmentIcon category={e.category} size={24}/></span><Status cert={cert}/></div><p className="equipment-category">{e.category}</p><h2>{e.name}</h2><p className="equipment-model">{[e.brand,e.model].filter(Boolean).join(' · ')||'Modelo não informado'}</p><dl><div><dt>Número de série</dt><dd className="serial">{e.serial}</dd></div><div><dt>Patrimônio</dt><dd>{e.tag||'Não informado'}</dd></div><div><dt>Última calibração</dt><dd>{cert?dateLabel(cert.calibratedAt):'Não informada'}</dd></div><div><dt>Próxima calibração</dt><dd>{cert?dateLabel(cert.nextAt):'Não informada'}</dd></div></dl><div className="equipment-location"><MapPin size={14}/>{e.location||'Localização não informada'}</div><button className="equipment-history" onClick={()=>details(e)}><History size={16}/>Ver histórico <span>{certificates.filter(c=>c.equipmentId===e.id).length}</span><ArrowRight size={16}/></button></article>;})}</div>:<div className="panel">{blank('Nenhum equipamento encontrado','Confira os filtros ou cadastre um equipamento para começar.',(query||category!=='all'||status!=='all')?<button className="button outline" onClick={()=>{setQuery('');setCategory('all');setStatus('all');}}>Limpar filtros</button>:isAdmin?<button className="button primary" onClick={()=>startAdd('equipment')}><Plus size={16}/>Cadastrar equipamento</button>:undefined)}</div>}</>}
      {view==='clients'&&(isAdmin||demo)&&<><div className="client-explanation"><ShieldCheck size={19}/><p>Cada cliente acessa apenas os equipamentos e certificados vinculados à sua empresa.</p></div>{data.companies.length?<div className="clients-grid">{data.companies.filter(c=>companyId==='all'||c.id===companyId).map(c=><article key={c.id} className="panel client-card"><div className="client-card-title"><span className="equipment-icon"><Building2 size={24}/></span><div><h2>{c.name}</h2><p>{c.cnpj||'CNPJ / CPF não informado'}</p></div><span className="context-tag">{demo?'EXEMPLO':'CLIENTE'}</span></div>{c.contact&&<p className="client-contact">{c.contact}</p>}<div className="client-numbers"><span><strong>{data.equipment.filter(e=>e.companyId===c.id).length}</strong> equipamentos</span><span><strong>{data.certificates.filter(cert=>data.equipment.some(e=>e.id===cert.equipmentId&&e.companyId===c.id)).length}</strong> certificados</span></div><div className="client-actions"><button className="button outline" onClick={()=>{setCompanyId(c.id);go('certificates');}}>Ver certificados <ArrowUpRight size={15}/></button><button className="button primary" disabled={busy} onClick={()=>invite(c)}><Link2 size={16}/>Gerar acesso</button></div><div className="member-list"><h3>Usuários com acesso</h3>{data.members.filter(m=>m.companyId===c.id).length?data.members.filter(m=>m.companyId===c.id).map(m=><div className="member" key={m.userId}><UserRound size={17}/><span><strong>{m.name}</strong><small>{m.email}</small></span><button className="icon-button" aria-label={`Remover acesso de ${m.name}`} title="Remover acesso" onClick={()=>setRevoke(m)}><X size={16}/></button></div>):<p>Nenhum usuário vinculado. Gere um código de acesso para este cliente.</p>}</div></article>)}</div>:<div className="panel">{blank('Seu primeiro cliente começa aqui','Cadastre a empresa para organizar seus equipamentos e certificados.',<button className="button primary" onClick={()=>startAdd('company')}><Plus size={16}/>Cadastrar cliente</button>)}</div>}<div className="access-note"><Info size={17}/><p>O portal está em acesso privado para implantação. A liberação para clientes externos depende da configuração de acesso do site. Os códigos vinculam cada usuário à empresa correta.</p></div></>}
      <footer className="page-footer"><span>© {new Date().getUTCFullYear()} Central Brasil Instrumentos</span><span><ShieldCheck size={14}/>Seu histórico. Sempre ao seu alcance.</span></footer>
      </>}
    </main></div>

    <Sheet open={!!selected} onOpenChange={o=>{if(!o)setSelected(null);}}><SheetContent className="equipment-sheet w-full sm:max-w-[620px]"><SheetHeader><p className="eyebrow">HISTÓRICO DO EQUIPAMENTO</p><SheetTitle>{selected?.name}</SheetTitle><SheetDescription>{selected?.brand} {selected?.model} · Série {selected?.serial}</SheetDescription></SheetHeader>{selected&&<div className="sheet-body"><div className="sheet-equipment-summary"><span className="equipment-icon"><EquipmentIcon category={selected.category} size={27}/></span><div><strong>{selected.serial}</strong><span>{selected.tag||'Sem patrimônio'} · {selected.location||'Local não informado'}</span></div><Status cert={latestFor(selected.id,certificates)}/></div><Tabs defaultValue="history"><TabsList className="sheet-tabs"><TabsTrigger value="history"><History size={15}/>Histórico de certificados</TabsTrigger><TabsTrigger value="details">Dados do equipamento</TabsTrigger></TabsList><TabsContent value="history"><p className="history-explanation">Todos os certificados do mesmo equipamento, organizados por data de calibração.</p><div className="timeline">{certificates.filter(c=>c.equipmentId===selected.id).map((c,i)=><article key={c.id} className={'timeline-item '+(selectedCert===c.id?'highlighted':'')}><span className="timeline-dot"><FileCheck2 size={16}/></span><div className="timeline-date">{dateLabel(c.calibratedAt)}{i===0&&<span>MAIS RECENTE</span>}</div><h3>{c.number}</h3><div className="timeline-meta"><span>Próxima calibração</span><strong>{dateLabel(c.nextAt)}</strong></div>{c.notes&&<p>{c.notes}</p>}<div className="timeline-actions"><button className="button outline" disabled={pdfBusy===c.id} onClick={()=>openPdf(c)}><Eye size={15}/>Visualizar PDF</button><button className="button text" disabled={pdfBusy===c.id} onClick={()=>openPdf(c,true)}><Download size={15}/>Baixar</button></div></article>)}</div>{!certificates.some(c=>c.equipmentId===selected.id)&&blank('Ainda sem certificados','O primeiro documento enviado aparecerá neste histórico.')}</TabsContent><TabsContent value="details"><dl className="detail-fields">{[['Equipamento',selected.name],['Categoria',selected.category],['Marca',selected.brand],['Modelo',selected.model],['Número de série',selected.serial],['Patrimônio',selected.tag],['Localização',selected.location],['Cliente',data.companies.find(c=>c.id===selected.companyId)?.name||'']].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v||'Não informado'}</dd></div>)}</dl></TabsContent></Tabs><div className="metrology-note"><Info size={16}/><p>A programação é definida pela próxima calibração cadastrada. Ela não representa uma validação automática do certificado ou da condição do equipamento.</p></div></div>}</SheetContent></Sheet>

    <Dialog open={!!modal} onOpenChange={o=>{if(!o&&!busy)setModal(null);}}><DialogContent className={modal==='help'?'form-dialog help-dialog':'form-dialog'}><DialogHeader><span className="dialog-icon">{modal==='company'?<Building2/>:modal==='equipment'?<Boxes/>:modal==='certificate'?<FileCheck2/>:modal==='access'?<ShieldCheck/>:<HelpCircle/>}</span><DialogTitle>{modal==='company'?'Cadastrar cliente':modal==='equipment'?'Cadastrar equipamento':modal==='certificate'?'Adicionar certificado':modal==='access'?'Vincular meu acesso':'Como usar o portal'}</DialogTitle><DialogDescription>{modal==='company'?'Organize os certificados por empresa.':modal==='equipment'?'Um cadastro único para todo o histórico do equipamento.':modal==='certificate'?'Envie o PDF original e vincule ao equipamento correto.':modal==='access'?'Use o código enviado pela Central Brasil.':'Certificados organizados, da consulta ao download.'}</DialogDescription></DialogHeader>
    {modal==='help'?<div className="help-content"><div><span>01</span><section><h3>Encontre seu equipamento</h3><p>Busque pelo nome, número de série, patrimônio ou número do certificado.</p></section></div><div><span>02</span><section><h3>Consulte todo o histórico</h3><p>Cada equipamento tem um cadastro próprio. Novas calibrações são adicionadas ao mesmo histórico, mesmo quando o número do certificado muda.</p></section></div><div><span>03</span><section><h3>Visualize ou baixe o PDF</h3><p>Use o ícone de visualização para abrir o documento e a seta de download para salvar o arquivo original.</p></section></div><div><span>04</span><section><h3>Acompanhe a programação</h3><p>Os avisos usam a data da próxima calibração informada. Um certificado sem essa data aparece como “Sem programação”.</p></section></div>{isAdmin&&<div className="help-admin"><strong>Para começar com seus dados</strong><p>Saia da demonstração, cadastre um cliente, adicione o equipamento e envie seu primeiro certificado. Em Clientes e acessos, gere um código para vincular cada usuário à empresa.</p><p>O acesso atual usa a conta ChatGPT e o portal permanece privado durante a implantação.</p></div>}<button className="button primary full-width" onClick={()=>setModal(null)}>Entendi <Check size={16}/></button></div>:<form onSubmit={e=>submit(e,modal)} className="portal-form">
      {modal==='company'&&<><Field label="Razão social / nome"><input name="name" placeholder="Ex.: Indústria Silva Ltda." required maxLength={200}/></Field><Field label="CNPJ / CPF" optional><input name="cnpj" placeholder="00.000.000/0000-00" maxLength={30}/></Field><Field label="Contato do cliente" optional><input name="contact" placeholder="Nome, e-mail ou telefone" maxLength={200}/></Field></>}
      {modal==='equipment'&&<><Field label="Cliente"><Picker label="Selecione o cliente" name="companyId" required defaultValue={companyId!=='all'&&companyId!=='demo'?companyId:real.companies[0]?.id} options={real.companies.map(c=>({value:c.id,label:c.name}))}/></Field><Field label="Nome do equipamento"><input name="name" placeholder="Ex.: Detector multigás" required maxLength={200}/></Field><Field label="Categoria"><Picker label="Selecione a categoria" name="category" required defaultValue={categories[0]} options={categories.map(c=>({value:c,label:c}))}/></Field><div className="form-grid"><Field label="Marca" optional><input name="brand" maxLength={100}/></Field><Field label="Modelo" optional><input name="model" maxLength={100}/></Field></div><div className="form-grid"><Field label="Número de série"><input name="serial" required maxLength={100} placeholder="Identificação do fabricante"/></Field><Field label="Patrimônio / tag" optional><input name="tag" maxLength={100}/></Field></div><Field label="Localização" optional><input name="location" placeholder="Ex.: Laboratório — Unidade 1" maxLength={200}/></Field></>}
      {modal==='certificate'&&<><Field label="Equipamento"><Picker label="Selecione o equipamento" name="equipmentId" required defaultValue={real.equipment.filter(e=>companyId==='all'||e.companyId===companyId)[0]?.id||real.equipment[0]?.id} options={real.equipment.map(e=>({value:e.id,label:`${e.name} · ${e.serial} · ${real.companies.find(c=>c.id===e.companyId)?.name}`}))}/></Field><Field label="Número do certificado"><input name="number" required maxLength={80} placeholder="Ex.: CB-2026-001842"/></Field><div className="form-grid"><Field label="Data da calibração"><input name="calibratedAt" type="date" required max={today()}/></Field><Field label="Próxima calibração" optional><input name="nextAt" type="date"/></Field></div><p className="field-hint">Informe a próxima data conforme a programação acordada com o cliente.</p><Field label="Arquivo do certificado"><span className="upload-field"><Upload size={23}/><strong>Selecione o PDF original</strong><small>Arquivo PDF com até 10 MB</small><input name="file" aria-label="Arquivo PDF do certificado" type="file" accept="application/pdf,.pdf" required/></span></Field><Field label="Observações" optional><textarea name="notes" placeholder="Informações relevantes sobre este documento" rows={3} maxLength={2000}/></Field></>}
      {modal==='access'&&<Field label="Código de acesso"><textarea name="code" rows={3} required maxLength={150} placeholder="Cole aqui o código recebido" autoComplete="off"/></Field>}
      {formError&&<div className="form-error" role="alert"><TriangleAlert size={16}/>{formError}</div>}<div className="form-actions"><button type="button" className="button outline" disabled={busy} onClick={()=>setModal(null)}>Cancelar</button><button className="button primary" type="submit" disabled={busy}>{busy?<LoaderCircle size={16} className="animate-spin"/>:<Check size={16}/>} {busy?'Salvando...':modal==='certificate'?'Salvar certificado':modal==='access'?'Vincular acesso':'Salvar cadastro'}</button></div>
    </form>}</DialogContent></Dialog>

    <Dialog open={!!pdf} onOpenChange={o=>{if(!o)setPdf(null);}}><DialogContent className="pdf-dialog"><DialogHeader><DialogTitle>{pdf?.number}</DialogTitle><DialogDescription>{demo?'PDF de demonstração — sem validade metrológica':'Certificado original enviado pela administração'}</DialogDescription></DialogHeader>{pdf&&<iframe title={`Certificado ${pdf.number}`} src={pdf.url}/>}<button className="button outline" onClick={()=>{if(pdf){const a=document.createElement('a');a.href=pdf.url;a.download=`${demo?'DEMONSTRACAO-':''}${pdf.number.replace(/[^a-zA-Z0-9_-]/g,'_')}.pdf`;a.click();}}}><Download size={16}/>Baixar PDF</button></DialogContent></Dialog>
    <Dialog open={!!invitation} onOpenChange={o=>{if(!o)setInvitation(null);}}><DialogContent className="form-dialog"><DialogHeader><span className="dialog-icon"><Link2/></span><DialogTitle>Código de acesso criado</DialogTitle><DialogDescription>{invitation?.company.name}</DialogDescription></DialogHeader><p className="invite-description">Este código vincula uma conta à empresa. É de uso único e expira em 7 dias.</p><textarea className="invite-code" aria-label="Código de acesso" readOnly value={invitation?.code||''}/><button className="button primary full-width" onClick={async()=>{try{await navigator.clipboard.writeText(invitation!.code);toast.success('Código copiado.');}catch{toast.info('Selecione o código acima e copie manualmente.');}}}><Copy size={16}/>Copiar código</button><p className="field-hint">Nenhuma mensagem foi enviada. A entrada de clientes externos também exige a liberação de acesso do site.</p></DialogContent></Dialog>
    <AlertDialog open={!!revoke} onOpenChange={o=>{if(!o&&!busy)setRevoke(null);}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Remover acesso?</AlertDialogTitle><AlertDialogDescription>{revoke?.name} deixará de consultar os equipamentos e certificados desta empresa. Os documentos serão mantidos.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel disabled={busy}>Cancelar</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={e=>{e.preventDefault();void revokeMember();}}>Remover acesso</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
    <Toaster position="bottom-right" richColors closeButton/>
  </SidebarProvider>;
}
